# Generated by Django 5.0.7 on 2024-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='badges/')),
                ('type', models.CharField(choices=[('streak', 'Streak'), ('habit', 'Habit'), ('challenge', 'Challenge')], max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
