# Generated by Django 5.0.7 on 2024-07-27 18:06

import Profile.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(default=Profile.models.generate_code, max_length=10, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('score', models.IntegerField(default=0)),
                ('streak_start', models.DateField(blank=True, null=True)),
                ('streak_end', models.DateField(blank=True, null=True)),
                ('notification_enabled', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
