# Generated by Django 5.0.7 on 2024-07-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notification_enabled',
            field=models.BooleanField(),
        ),
    ]
