# Generated by Django 5.0.7 on 2024-08-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badge', '0001_initial'),
        ('Profile', '0007_score'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS Profile_userbadge',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='Badge.badge')),
                ('profile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(
                through='Profile.UserBadge', to='Badge.badge'),
        ),
    ]
