# Generated by Django 5.0.7 on 2024-08-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_alter_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_challenges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='completed_habits',
            field=models.IntegerField(default=0),
        ),
    ]
