# Generated by Django 5.0.7 on 2024-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badge', '0001_initial'),
        ('Profile', '0011_profile_completed_challenges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, through='Profile.UserBadge', to='Badge.badge'),
        ),
    ]
