# Generated by Django 5.0.7 on 2024-08-05 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0004_alter_habit_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitinstance',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 8, 5)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitinstance',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
