# Generated by Django 5.0.7 on 2024-08-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0005_habitinstance_due_date_habitinstance_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='modify_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
