# Generated by Django 5.0.7 on 2024-08-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0006_habit_modify_date_alter_habit_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitinstance',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
