# Generated by Django 5.0.7 on 2024-08-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0007_alter_habitinstance_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='from_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
