# Generated by Django 5.0.7 on 2024-08-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0008_habit_from_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Habit.tag'),
        ),
    ]
