# Generated by Django 5.0.7 on 2024-08-09 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0003_alter_challenge_participants'),
        ('Habit', '0010_alter_habit_from_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='from_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants_habits', to='Challenge.challenge'),
        ),
    ]
