# Generated by Django 5.0.7 on 2024-08-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0011_alter_habit_from_challenge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
