# Generated by Django 5.0.7 on 2024-08-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0012_delete_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
