# Generated by Django 5.0.7 on 2024-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_track_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
